/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
	ignoredRouteFiles: ['**/.*'],
	// appDirectory: "app",
	// assetsBuildDirectory: "public/build",
	// serverBuildPath: "build/index.js",
	// publicPath: "/build/",
	server: process.env.NETLIFY || process.env.NETLIFY_LOCAL ? "./server.js" : undefined,
  serverBuildPath: ".netlify/functions-internal/server.js",
	serverDependenciesToBundle: [
		// remix ESM issue: https://github.com/remix-run/remix/issues/109#issuecomment-1100583571
		/^rehype.*/,
		/^remark.*/,
		/^unified.*/,
		/^unist.*/,
		/^hast.*/,
		/^bail.*/,
		/^trough.*/,
		/^mdast.*/,
		/^micromark.*/,
		/^decode.*/,
		/^character.*/,
		/^property.*/,
		/^space.*/,
		/^comma.*/,
		/^react-markdown$/,
		/^vfile.*/,
		'trim-lines',
		'stringify-entities',
		'parse-entities',
		'lowlight',
		'is-decimal',
		'is-hexadecimal',
		'is-alphanumerical',
		'is-alphabetical',
		'is-plain-obj',
		'is-buffer',
		'fault'
	],
	future: {
		unstable_tailwind: true,
	},
};
